In [20]:
import pandas as pd 

import numpy as np

In [21]:
df = pd.read_csv(r"E:\resume_project\ai-interview-analyzer\data\processed\training_features.csv")

In [3]:
df.head()

,image_name,emotion,avg_ear,left_ear,right_ear,blink_flag,smile_ratio,eye_sync,head_pitch,head_yaw,head_roll,eye_gaze_direction
0,Training_10120469.jpg,angry,0.251542,0.278678,0.224407,0,116.481346,0.054271,-162.219905,-11.086761,8.254448,-1
1,Training_1021836.jpg,angry,0.264913,0.266978,0.262848,0,4.108315,0.004130,178.544809,-2.050025,-9.457204,-1
2,Training_10269675.jpg,angry,0.279311,0.252179,0.306444,0,5.256446,0.054265,-165.259345,7.208128,-0.616804,1
3,Training_10278738.jpg,angry,0.082492,0.072637,0.092347,0,37.531395,0.019710,-171.993667,2.083817,-10.806550,-1
4,Training_10290703.jpg,angry,0.211528,0.122159,0.300896,0,1.541642,0.178736,176.763678,38.887708,-7.851196,1

In [22]:
df = df.drop("image_name",axis=1)

In [5]:
df.head()

,emotion,avg_ear,left_ear,right_ear,blink_flag,smile_ratio,eye_sync,head_pitch,head_yaw,head_roll,eye_gaze_direction
0,angry,0.251542,0.278678,0.224407,0,116.481346,0.054271,-162.219905,-11.086761,8.254448,-1
1,angry,0.264913,0.266978,0.262848,0,4.108315,0.004130,178.544809,-2.050025,-9.457204,-1
2,angry,0.279311,0.252179,0.306444,0,5.256446,0.054265,-165.259345,7.208128,-0.616804,1
3,angry,0.082492,0.072637,0.092347,0,37.531395,0.019710,-171.993667,2.083817,-10.806550,-1
4,angry,0.211528,0.122159,0.300896,0,1.541642,0.178736,176.763678,38.887708,-7.851196,1

In [6]:
from sklearn.preprocessing import StandardScaler 
from sklearn.model_selection import train_test_split

In [23]:
X = df.drop("emotion",axis=1)
y = df["emotion"]

In [8]:
# print(y.unique())

# label = {
#     'angry' : 0,
#     'disgust':1,
#     'fear' :2,
#     'happy':3,
#     'neutral' :4,
#     'sad' :5,
#     'surpise' :6
# }

In [24]:
from sklearn.preprocessing import LabelEncoder ,StandardScaler

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print(np.unique(y_encoded))

[0 1 2 3 4 5 6]

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.ensemble import RandomForestClassifier

Model = RandomForestClassifier(
    n_estimators=700,
    max_depth=30,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

Model.fit(X_train_scaled, y_train)

RandomForestClassifier(max_depth=30, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=700, n_jobs=-1, random_state=42)

In [13]:
from sklearn.metrics import accuracy_score, classification_report

y_pred_train = Model.predict(X_train_scaled)
y_pred_test = Model.predict(X_test_scaled)

print("Train Accuracy:", accuracy_score(y_train, y_pred_train))
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))

print(classification_report(y_test, y_pred_test))

Train Accuracy: 0.9742125889012531
Test Accuracy: 0.4748452012383901
              precision    recall  f1-score   support

           0       0.45      0.22      0.29       679
           1       1.00      0.19      0.32        74
           2       0.37      0.17      0.23       711
           3       0.53      0.70      0.61      1357
           4       0.40      0.57      0.47       942
           5       0.39      0.34      0.36       800
           6       0.59      0.69      0.64       605

    accuracy                           0.47      5168
   macro avg       0.53      0.41      0.42      5168
weighted avg       0.47      0.47      0.45      5168

In [14]:
from sklearn.ensemble import GradientBoostingClassifier

Model = GradientBoostingClassifier(
    learning_rate=0.1,
    max_depth=5,
    n_estimators=300,
    random_state=42
)

Model.fit(X_train_scaled, y_train)

y_pred_train = Model.predict(X_train_scaled)
y_pred_test = Model.predict(X_test_scaled)

print("Train Accuracy:", accuracy_score(y_train, y_pred_train))
print("Test Accuracy:", accuracy_score(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))

Train Accuracy: 0.7602206202525521
Test Accuracy: 0.4485294117647059
              precision    recall  f1-score   support

           0       0.41      0.19      0.26       679
           1       0.44      0.24      0.31        74
           2       0.31      0.14      0.19       711
           3       0.53      0.68      0.60      1357
           4       0.37      0.55      0.44       942
           5       0.37      0.31      0.34       800
           6       0.55      0.64      0.59       605

    accuracy                           0.45      5168
   macro avg       0.43      0.39      0.39      5168
weighted avg       0.43      0.45      0.42      5168

In [15]:
# from xgboost import XGBClassifier

# model = XGBClassifier(
#     n_estimators=100,
#     learning_rate=0.4,
#     eval_metric="logloss",
#     random_state=42
# )
# model.fit(X_train_scaled,y_train)

In [16]:
# y_pred_train = Model.predict(X_train_scaled)

In [17]:
# y_pred_train = Model.predict(X_train_scaled)
# y_pred_test = Model.predict(X_test_scaled)

# print("Train Accuracy:", accuracy_score(y_train, y_pred_train))
# print("Test Accuracy:", accuracy_score(y_test, y_pred_test))
# print(classification_report(y_test, y_pred_test))

In [29]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.utils.class_weight import compute_class_weight
from xgboost import XGBClassifier
from scipy.stats import randint, uniform

# Build class weights from training labels, then upweight classes with lowest recall.
classes = np.unique(y_train)
base_weights = compute_class_weight(class_weight="balanced", classes=classes, y=y_train)
class_weight_map = {int(c): float(w) for c, w in zip(classes, base_weights)}

# Extra emphasis for minority / hard classes: angry(0), disgust(1), fear(2)
for cls in [0, 1, 2]:
    if cls in class_weight_map:
        class_weight_map[cls] *= 1.25

sample_weight_train = np.array([class_weight_map[int(label)] for label in y_train], dtype=np.float32)

rf = RandomForestClassifier(random_state=42, n_jobs=-1)
rf_param_dist = {
    "n_estimators": randint(300, 1000),
    "max_depth": [None, 10, 20, 30, 40],
    "min_samples_split": randint(2, 12),
    "min_samples_leaf": randint(1, 6),
    "max_features": ["sqrt", "log2", None],
    "bootstrap": [True, False],
    "class_weight": [class_weight_map, "balanced", "balanced_subsample"],
}

xgb = XGBClassifier(
    objective="multi:softmax",
    num_class=len(np.unique(y_train)),
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1,
)
xgb_param_dist = {
    "n_estimators": randint(200, 900),
    "max_depth": randint(3, 10),
    "learning_rate": uniform(0.02, 0.23),
    "subsample": uniform(0.65, 0.35),
    "colsample_bytree": uniform(0.65, 0.35),
    "min_child_weight": randint(1, 8),
    "gamma": uniform(0.0, 0.4),
    "reg_alpha": uniform(0.0, 0.4),
    "reg_lambda": uniform(0.7, 1.8),
}

rf_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=rf_param_dist,
    n_iter=12,
    scoring="f1_macro",
    cv=3,
    verbose=0,
    random_state=42,
    n_jobs=-1,
)

xgb_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=xgb_param_dist,
    n_iter=12,
    scoring="f1_macro",
    cv=3,
    verbose=0,
    random_state=42,
    n_jobs=-1,
)

rf_search.fit(X_train_scaled, y_train)
xgb_search.fit(X_train_scaled, y_train, sample_weight=sample_weight_train)

print("Class weight map:", class_weight_map)
print("Best RF CV Macro-F1:", rf_search.best_score_)
print("Best RF Params:", rf_search.best_params_)
print("Best XGB CV Macro-F1:", xgb_search.best_score_)
print("Best XGB Params:", xgb_search.best_params_)

Class weight map: {0: 1.3599457837667122, 1: 12.427248677248677, 2: 1.2986955866090277, 3: 0.5439783135066849, 4: 0.784045216599651, 5: 0.9230116554280355, 6: 1.2186191851895525}
Best RF CV Macro-F1: 0.40915391333084655
Best RF Params: {'bootstrap': True, 'class_weight': 'balanced_subsample', 'max_depth': 20, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 5, 'n_estimators': 861}
Best XGB CV Macro-F1: 0.38290945923973707
Best XGB Params: {'colsample_bytree': np.float64(0.8592649925838798), 'gamma': np.float64(0.36874969400924673), 'learning_rate': np.float64(0.04035327547194149), 'max_depth': 9, 'min_child_weight': 4, 'n_estimators': 495, 'reg_alpha': np.float64(0.3378135394712606), 'reg_lambda': np.float64(2.045176198247286), 'subsample': np.float64(0.8388922463361779)}

In [30]:
best_rf = rf_search.best_estimator_
best_xgb = xgb_search.best_estimator_

rf_test_pred = best_rf.predict(X_test_scaled)
xgb_test_pred = best_xgb.predict(X_test_scaled)

print("===== Tuned RandomForest =====")
print("Test Accuracy:", accuracy_score(y_test, rf_test_pred))
print(classification_report(y_test, rf_test_pred, target_names=label_encoder.classes_))

print("===== Tuned XGBoost =====")
print("Test Accuracy:", accuracy_score(y_test, xgb_test_pred))
print(classification_report(y_test, xgb_test_pred, target_names=label_encoder.classes_))

===== Tuned RandomForest =====
Test Accuracy: 0.46904024767801855
              precision    recall  f1-score   support

       angry       0.42      0.23      0.30       679
     disgust       0.81      0.28      0.42        74
        fear       0.37      0.17      0.24       711
       happy       0.56      0.66      0.61      1357
     neutral       0.39      0.56      0.46       942
         sad       0.38      0.34      0.36       800
    surprise       0.56      0.70      0.62       605

    accuracy                           0.47      5168
   macro avg       0.50      0.42      0.43      5168
weighted avg       0.46      0.47      0.45      5168

===== Tuned XGBoost =====
Test Accuracy: 0.45239938080495357
              precision    recall  f1-score   support

       angry       0.35      0.32      0.33       679
     disgust       0.47      0.32      0.38        74
        fear       0.29      0.22      0.25       711
       happy       0.60      0.59      0.60      1357
     neutral       0.39      0.47      0.43       942
         sad       0.36      0.34      0.35       800
    surprise       0.57      0.70      0.63       605

    accuracy                           0.45      5168
   macro avg       0.43      0.42      0.42      5168
weighted avg       0.45      0.45      0.45      5168

In [31]:
from joblib import dump

dump(best_rf, "tuned_randomforest_model.joblib")
print("Saved: tuned_randomforest_model.joblib")

Saved: tuned_randomforest_model.joblib